POST http://localhost:8080/cinel/api/v1/films?page=0
Content-Type: application/json

{
  "filter": {
    "year": 2002,
    "countries": [
      {
        "name": "ru"
      },
      {
        "name": "en"
      }
    ],
    "genres": [
      {
        "name": "genre"
      }
    ]
  },
  "search": {
    "name": "name"
  }
}
