###create room
POST localhost:8080/cinel/api/v1/rooms
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJST0xFIjoiVVNFUiIsInN1YiI6ImVsaW5hXzNzaGFAbWFpbC5ydSIsImV4cCI6MTY1MzIzMzAwNCwiaWF0IjoxNjUzMjMyNDA0fQ.YE34irUSKzwQ5U0ohJ_5a8_nVMeXvTqYLMQfUHmnGHfKG7cFTgJCzLa5ktOI7AWfvx36UoPdOyBz8NxRO-iDyQ

###change film
PUT localhost:8080/cinel/api/v1/rooms/247b724b-cac0-403c-b0c3-e8891fa73d1a/film?filmId=247b724b-cac0-403c-b0c3-e8891fa73d5a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJST0xFIjoiVVNFUiIsInN1YiI6ImVsaW5hXzNzaGFAbWFpbC5ydSIsImV4cCI6MTY1MzIzMzY3NiwiaWF0IjoxNjUzMjMzMDc2fQ.XqugWYURK5UvWfcYEEvMWcdzoMmoub4hLUYdli0GFodhrn0765FKpr26DXcfe1D2WKDs7dHuHB1KOcCJHjwpBg
###delete film
DELETE localhost:8080/cinel/api/v1/rooms/247b724b-cac0-403c-b0c3-e8891fa73d1a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJST0xFIjoiVVNFUiIsInN1YiI6ImVsaW5hXzNzaGFAbWFpbC5ydSIsImV4cCI6MTY1MzIzMzAwNCwiaWF0IjoxNjUzMjMyNDA0fQ.YE34irUSKzwQ5U0ohJ_5a8_nVMeXvTqYLMQfUHmnGHfKG7cFTgJCzLa5ktOI7AWfvx36UoPdOyBz8NxRO-iDyQ
